
import { StatType, Boss } from './types';

export const BASE_QUESTS = [
  { id: 'q1', label: 'Pullups PR x2', xp: 50, coins: 5, type: 'DAILY' },
  { id: 'q2', label: 'Pushups PR x2', xp: 50, coins: 5, type: 'DAILY' },
  { id: 'q3', label: 'Squats PR x2', xp: 50, coins: 5, type: 'DAILY' },
  { id: 'q4', label: '7000 Steps', xp: 75, coins: 10, type: 'DAILY' },
  { id: 'q5', label: '10 Minutes Fresh Air', xp: 50, coins: 5, type: 'DAILY' },
  { id: 'q6', label: 'Stretching 5 Muscles', xp: 45, coins: 5, type: 'DAILY' },
  { id: 'q7', label: 'Caring for Wrists/Neck (5m)', xp: 30, coins: 5, type: 'DAILY' },
  { id: 'q8', label: 'Stamina (30 min sport)', xp: 50, coins: 10, type: 'DAILY' },
];

export const HARDCORE_MANDATORY = [
  { id: 'h1', label: 'Stretching (15m)', xp: 40, coins: 5, type: 'HARDCORE' },
  { id: 'h2', label: 'Mobility (10m)', xp: 40, coins: 5, type: 'HARDCORE' },
  { id: 'h3', label: 'Sleep (7-9h)', xp: 60, coins: 10, type: 'HARDCORE' },
];

export const PR_TIERS: Record<string, number[]> = {
  [StatType.Strength1]: [5, 15, 25, 33, 42, 50],
  [StatType.Strength2]: [30, 65, 100, 150, 200, 250],
  [StatType.Strength3]: [25, 55, 90, 140, 200, 250],
  [StatType.Stamina]: [10, 15, 20, 30, 40, 50],
  [StatType.Reaction]: [0.35, 0.30, 0.25, 0.22, 0.19, 0.16], // Lower is better
  [StatType.Vitality]: [6, 6.5, 7, 7.3, 7.6, 8],
};

export const BOSSES: Boss[] = [
  { id: 'b1', name: 'Miniboss', type: 'MINI', requirement: 'Streak ≥ 5 days', scaling: 3, rewardXp: 250, rewardCoins: 175, cooldownDays: 10 },
  { id: 'b2', name: 'Elite Boss', type: 'ELITE', requirement: 'Streak ≥ 10 days', scaling: 5, rewardXp: 500, rewardCoins: 250, cooldownDays: 20 },
  { id: 'b3', name: 'Legendary Boss', type: 'LEGENDARY', requirement: 'Streak ≥ 14 days', scaling: 8, rewardXp: 1000, rewardCoins: 500, cooldownDays: 28 },
  { id: 'b4', name: 'Mythic Boss', type: 'MYTHIC', requirement: 'Streak ≥ 20 days', scaling: 10, rewardXp: 1500, rewardCoins: 750, cooldownDays: 42 },
  { id: 'b5', name: 'Final Boss', type: 'FINAL', requirement: 'Streak ≥ 30 days', scaling: 13, rewardXp: 2000, rewardCoins: 1000, cooldownDays: 365 },
];

export const RANDOM_QUESTS = [
  "Walk backwards for 2 minutes without falling",
  "Make a hat out of paper and wear it for 30 min",
  "Balance a book on your head while doing 10 squats",
  "Speak in rhymes for 10 sentences",
  "Draw a monster with your non-dominant hand",
  "Do pushups while saying the alphabet",
  "Tape a coin to your forehead and keep it there 1 min",
  "Walk like a crab for 20 meters",
  "Make a tower from cups or blocks as tall as your knee",
  "Talk to a plant like it’s your best friend for 5 min",
  "Make a paper airplane and throw it across the room",
  "Eat a bite of something blindfolded and guess what it is",
  "Hold a squat while balancing a small object on your head",
  "Write a 4-line poem about your day",
  "Do 5 jumping jacks while spinning in a circle",
  "Record yourself saying a joke in a dramatic voice",
  "Walk around the house pretending to be a ninja",
  "Fold an origami animal",
  "Do 10 pushups on one arm (or attempt it)",
  "Pretend you’re a cat for 3 minutes (stretch, crawl, meow)",
  "Make a “treasure map” of your room",
  "Draw your dream house in 2 minutes",
  "Balance a spoon on your nose for 30 seconds",
  "Do 10 burpees but clap above your head like a seal",
  "Say a tongue twister 5 times fast",
  "Make a 10-second dance video for no reason",
  "Walk on your toes only for 5 minutes",
  "Try to do 5 pullups while singing",
  "Create a “signature move” like a superhero",
  "Stack 5 random objects without them falling",
  "Build a tiny obstacle course for yourself",
  "Eat something with chopsticks only",
  "Try to juggle 3 small objects",
  "Pretend to be a statue for 1 min without moving",
  "Write a 3-line story using only emojis",
  "Draw a self-portrait using only circles",
  "Hold a wall-sit while reciting a poem",
  "Do 10 lunges while naming countries in alphabetical order",
  "Pretend to be a robot for 5 min",
  "Make up a handshake with yourself",
  "Do pushups with claps in between",
  "Walk around balancing a small object on your hand",
  "Speak in a foreign accent for 5 min",
  "Make a funny hat from trash",
  "Do 20 frog jumps while humming",
  "Write a mini rap about brushing your teeth",
  "Try to touch your toes while balancing on one leg",
  "Make a “tiny workout circuit” in 5 min with furniture",
  "Speak only in questions for 3 minutes",
  "Pretend to be underwater while moving around the room",
  "Draw an animal with your eyes closed",
  "Clap hands in a weird pattern for 30 sec",
  "Make a funny face and hold it 1 min",
  "Balance a pen on your finger for 30 sec",
  "Try a new yoga pose you’ve never done",
  "Write a message to a future version of yourself",
  "Stack shoes in a tower without toppling them",
  "Do a slow-motion sprint around the room",
  "Say the alphabet backward while doing squats",
  "Draw a “map of your day” in symbols",
  "Build a bridge from random objects",
  "Try to stand on one foot with eyes closed for 1 min",
  "Do 15 pushups while pretending to be a superhero",
  "Make a tiny sculpture from anything on your desk",
  "Talk to a pet or stuffed animal like it’s human",
  "Try to hop on one leg while counting to 30",
  "Walk like a zombie for 5 minutes",
  "Make a funny sign and put it somewhere in your room",
  "Draw your own “emoji version”",
  "Do 10 “invisible jump ropes”",
  "Balance 3 coins on each finger",
  "Pretend to be a pirate while doing daily tasks",
  "Speak gibberish for 1 minute",
  "Try to roll like a log across a soft surface",
  "Make a “secret handshake” with yourself",
  "Write a 2-line song and sing it dramatically",
  "Pretend to be in slow motion for 3 min",
  "Create a mini obstacle course for one sock",
  "Balance a book on your foot while lying down",
  "Draw your shadow as a monster",
  "Do 10 pushups while pretending to dodge lasers",
  "Make a small tower of random objects and knock it down safely",
  "Write a motivational quote but only 5 words",
  "Pretend to moonwalk across the room",
  "Build a “fort” using cushions or blankets",
  "Stand like a superhero for 1 min",
  "Do 10 wall handstands (or try)",
  "Make up a new handshake with a pet or friend",
  "Hop 20 times like a bunny",
  "Draw a map of your city from memory",
  "Pretend to be a mime for 2 minutes",
  "Try to balance on a chair edge safely",
  "Do pushups while humming your favorite song",
  "Speak like a news reporter for 3 min",
  "Write a haiku about your breakfast",
  "Do 15 “air punches” like a boxer",
  "Try a new way to tie your shoelaces",
  "Make a “funny face challenge” in the mirror",
  "Walk around carrying an imaginary heavy object",
  "Do 10 squats while pretending to be a king/queen",
  "Write a “fake ad” for a household object",
  "Do 10 “air squats” while spinning in place",
  "Make a mini paper boat and float it in water",
  "Talk to your reflection for 2 minutes like it’s a stranger",
  "Walk sideways across the room",
  "Try to balance on one hand while sitting (or attempt)",
  "Write a silly story using 5 random words",
  "Do 20 slow-motion jumping jacks",
  "Fold 3 origami cranes",
  "Draw a face on your hand and act like it’s alive",
  "Make a short 1-min shadow puppet story",
  "Walk on your heels for 50 meters",
  "Pretend to lift an invisible heavy object 10 times",
  "Try to spin a pen on your finger 10 times",
  "Sing your favorite song backward (or just lyrics backward)",
  "Make a tiny “crown” from paper and wear it for 10 min",
  "Write a haiku about your shoes",
  "Crawl like a spy for 5 meters",
  "Build a “furniture maze” and navigate it",
  "Draw a random map of your room",
  "Balance a bottle on your head for 1 min",
  "Do 10 pushups while humming a tune",
  "Speak like a robot for 3 min",
  "Make a funny face and hold it 30 seconds",
  "Clap your hands in a weird rhythm for 30 sec",
  "Walk backwards while counting to 20",
  "Create a handshake with your reflection",
  "Do 15 “air punches” while shouting like a boxer",
  "Try to toss a small object and catch it with your toes",
  "Pretend to be a statue for 2 min",
  "Draw a monster with 3 eyes and 4 arms",
  "Do 10 lunges while saying random numbers",
  "Build a card tower of at least 5 cards",
  "Jump 10 times in a weird pattern (left, right, spin)",
  "Pretend to be underwater while walking 10 meters",
  "Make a “funny hat” from a towel",
  "Balance a small object on your finger while walking",
  "Speak in gibberish for 2 min",
  "Try a new handstand variation",
  "Write a motivational note and hide it somewhere",
  "Do 15 frog jumps in place",
  "Make a paper ring and wear it",
  "Pretend you’re a secret agent for 5 min",
  "Walk like a dinosaur for 1 min",
  "Write a 3-line rap about your day",
  "Do 10 “reverse pushups” (on knees, slow)",
  "Build a tiny obstacle course with toys",
  "Hop like a kangaroo 10 meters",
  "Speak like a pirate for 3 min",
  "Draw a comic strip in 5 min",
  "Balance a cup on your foot for 30 sec",
  "Walk 5 meters like a ballerina on toes",
  "Pretend you’re a superhero flying around",
  "Make a tower of books and knock it down safely",
  "Act like a robot doing chores for 5 min",
  "Try to touch your nose with your tongue",
  "Do 20 squats while singing a song",
  "Make a tiny musical instrument from random objects",
  "Pretend to be a mime for 2 min",
  "Walk with arms stiff like a zombie",
  "Draw a “monster” using only triangles",
  "Balance 3 objects on your head",
  "Hop on one leg while spinning in circles",
  "Pretend to be invisible for 1 min",
  "Write a joke and tell it dramatically",
  "Crawl under a chair slowly",
  "Do 10 slow pushups while counting backward",
  "Stack 5 coins on top of each other",
  "Make a funny obstacle out of cushions",
  "Speak only in questions for 1 min",
  "Pretend to be a cat walking around",
  "Do 10 air squats with arms crossed",
  "Make a “tiny fort” from paper",
  "Act like you’re in slow motion for 2 min",
  "Balance a pen on your nose 30 sec",
  "Walk sideways and clap hands every 3 steps",
  "Write a short story about an invisible friend",
  "Do 10 pushups with one leg raised",
  "Build a mini bridge from random items",
  "Pretend to be a monkey for 2 min",
  "Draw a self-portrait using only squares",
  "Clap hands in a random rhythm for 1 min",
  "Walk like a crab for 10 meters",
  "Make up a new handshake with yourself",
  "Pretend to jump over lava while doing lunges",
  "Stack plastic cups in a pyramid",
  "Walk 5 meters balancing a small object on your hand",
  "Do 10 slow-motion mountain climbers",
  "Speak in a funny accent for 3 min",
  "Draw an imaginary map of your city",
  "Pretend to be a statue that comes alive suddenly",
  "Hop in a circle 5 times",
  "Write a poem about your socks",
  "Balance a coin on your finger 30 sec",
  "Pretend to row a boat for 2 min",
  "Jump and spin while counting to 5",
  "Act like a robot for 5 min while doing chores",
  "Build a “trap” for a toy and then disarm it",
  "Do pushups while pretending to dodge lasers",
  "Walk like a ballerina on tiptoes while humming"
];
